name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4

    - name: Setup Java JDK
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8

    - name: Cache Gradle packages
      uses: actions/cache@v2.1.3
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: ${{ runner.os }}-gradle

    - name: Grant execute permission for gradlew
      if: runner.os == 'Linux' || runner.os == 'macOS'
      run: chmod +x gradlew

    - name: Run Tests with Gradle
      run: ./gradlew test

    - name: Upload artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        name: test-result-${{ runner.os }}
        path: build/reports/tests
